---
version: 1

build_arg_defaults:
# Due to: https://bugzilla.redhat.com/show_bug.cgi?id=2018659
  EE_BASE_IMAGE: 'image-registry.openshift-image-registry.svc:5000/openshift/ee-minimal-rhel8:1.0.0-48'
  EE_BUILDER_IMAGE: 'image-registry.openshift-image-registry.svc:5000/openshift/ansible-automation-platform-21/ansible-builder-rhel8:1.0.1-28'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'

ansible_config: './ansible.cfg'

dependencies:
  galaxy: ./requirements.yml
  python: ./requirements.txt
  system: ./bindep.txt

additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
